### ISSUE TITLE
Revoke check happens before signature/expiry check

### ISSUE THREAD

**Issue by shayanelhami** [auth0/express-jwt#100]
The middleware first calls `isRevokedCallback` and then `jwt.verify()` [here](https://github.com/auth0/express-jwt/blob/master/lib/index.js#L87).

However for the most of the cases token-revocation-check needs a database or network call and is more expensive than a signature or expiry check. In normal scenarios if the token is invalid or expired, the request is unauthorized anyway and there is no need to check the revocation database.

Is it possible to consider changing the order of these checks?

**Comment by jfromaniello** [comment]
Thanks, fixed in `v3.2.0`
