### ISSUE TITLE
Token exp

### ISSUE THREAD

**Issue by emerak** [auth0/express-jwt#105]
In this case

 var token = jwt.sign({ unit: unit.id, exp: 1382412921 }, config.secret);

is the number in exp miliseconds? I just grab it from the test suite though and it should fail but which should not?

**Comment by jfromaniello** [comment]
I am very sorry for the long delay.. in case anyone else found this question the answer is exp is a unix timestamp:

- https://tools.ietf.org/html/rfc7519#section-4.1.4

> A JSON numeric value representing the number of seconds from
      1970-01-01T00:00:00Z UTC until the specified UTC date/time,
      ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
      2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
      which each day is accounted for by exactly 86400 seconds, other
      than that non-integer values can be represented.  See RFC 3339
      [RFC3339] for details regarding date/times in general and UTC in
      particular.
