### ISSUE TITLE
Is error due to a TokenExpiredError or an invalid token

### ISSUE THREAD

**Issue by edoecohen** [auth0/express-jwt#107]
This issue was initially posted as issue #15 but the solution there is not working.

express-jwt returns 401 when trying to access with an invalid token or an expired one. Is there a way to know the 401 was returned due to an expired token?

For expired tokens jsonwebtoken returns 

```javascript
{  [TokenExpiredError: jwt expired]
  name: 'TokenExpiredError',
  message: 'jwt expired'
}
```

Would be great if express-jwt would return something similar for expired tokens.
Thanks!

**Comment by jfromaniello** [comment]
This is what we currently do. Sorry for the long delay.

**Comment by jfromaniello** [comment]
Yes, you are right. We should be doing this.

**Comment by jfromaniello** [comment]
You can get the details of the jwt error with `err.inner`.

**Comment by sirbrillig** [comment]
@jfromaniello I'm sure I'm just missing something obvious, but how do you get the `err` object? 

I tried adding another middleware after the jwt middleware [as the README seems to suggest](https://github.com/auth0/express-jwt#error-handling) but the middleware is never reached.

My code:

```js
app.use( '/secured', jwt( {
  secret: new Buffer( process.env.AUTH0_CLIENT_SECRET, 'base64' ),
  audience: process.env.AUTH0_CLIENT_ID
} ) );
app.use( function( err, req, res, next ) {
  if ( err.name === 'UnauthorizedError' ) {
    console.log( 'error is', err );
  }
} );
```

**Comment by sirbrillig** [comment]
Nevermind! Just like that I figured it out. I think I wasn't registering the error handler at the end of all the other middleware. Rubber duck debugging. 🙃
