### ISSUE TITLE
Only supports HMAC hash, no support for RSASSA and ECDSA

### ISSUE THREAD

**Issue by narendrasoni1989** [auth0/express-jwt#109]
I am getting below error when i used RS256,RS384, RS512, ES256, ES384, ES512 for signing token.
As supported by [node-jsonwebtooken](https://github.com/auth0/node-jsonwebtoken)

<h3>"JsonWebTokenError: invalid algorithm"</h3>

**Comment by stantoncbradley** [comment]
+1 need this support also

**Comment by jfromaniello** [comment]
You need to call with `algorithms: ["RS256", "RS384"]` , provider the list of algorhitms that you support. Otherwise the library will try to guess by using the "public key" you provide.

I suspect that the public key you are providing doesn't start `BEGIN CERTIFICATE` nor `BEGIN PUBLIC KEY`? Is that correct?

Check this:

https://github.com/auth0/node-jsonwebtoken/blob/master/index.js#L184

**Comment by narendrasoni1989** [comment]
I am doing the same thing for signing the token.
```
var cert = fs.readFileSync('key.pem');
var token = jwt.sign({email: user.local.email, role : user.role, name : user.local.name}, cert,     { algorithm: 'HS512'});
```
express-jet works perfectly fine if token is signed with 'HS256','HS384','HS512' whereas it is breaking if we use any other algorithm form signing token such as 'RS256','RS384','RS512','ES256','ES384','ES512'.

**Comment by jfromaniello** [comment]
in the snippet you show here you are using an asymmetric key to sign with a symmetric algorithm. 

Second, can you show me the first line of the certificate you pass to express-jwt?

**Comment by zzswang** [comment]
Hi, I met the same problem.   

I sign token with RS256 algorithm

```
 jwt.sign(user, cert, {algorithm: 'RS256'}, function(err, token) {
      return res.json({
        user: wrapUser(user),
        token
      });
    });
```

My ras files are generated by ssh-keygen command. ( Is it right? )

The first line of pub file:

```
ssh-rsa 
AAAAB3NzaC1yc2EAAAADAQABAAABAQDE6uyXSgPAOb6+79O
```

**Comment by jfromaniello** [comment]
@zzswang rs256 is symmetric alg and you cant sign a jwt using this type of key.

**Comment by jfromaniello** [comment]
I am closing this issue because there is a lot of unrelated questions, and the feature described in the title has been supported since the beginning and the author didn't provide more details.

**Comment by bernardoadc** [comment]
@jfromaniello RS256 is asymmetric alg, stands for RSA with SHA 256
