### ISSUE TITLE
Can I plugin another middleware after express-jwt so i can take advantage of req.user?

### ISSUE THREAD

**Issue by XiSmartElf** [auth0/express-jwt#115]
I basically i want to achieve the following:
router.use(function (req, res) {
    res.user = req.user;
});

but this middileware is before express-jwt so req.user is undefined. is it possible to insert this middle ware to the end

**Comment by XiSmartElf** [comment]
i figured it out later.

**Comment by iaacek** [comment]
Could you please share how and put an example here?

**Comment by iaacek** [comment]
Figured it out. I wanted to check the role of the user after the jwt check, here is what I did:

the simplified check role function:

```javascript
function checkRole (role) {
    return function(req, res, next) {
        let userRole = req.user.user.role; // req.user stores an object user with role property in my case
        if (userRole = 'admin') next(); // just an example, I am have 3 different roles in the app 
        else return res.status(401);    // so the logic is more complex
    }
}
```
Route:
```javascript
router.get('/notes', ejwt({ secret: 'superSecret' }), checkRole('admin'), async (req, res) => {
    // connect to the db and get the notes
});
