### ISSUE TITLE
Clear 401 body

### ISSUE THREAD

**Issue by XiSmartElf** [auth0/express-jwt#117]
express-jwt always protect the api with 401 with error stack in response body. This is bad since you dont' want to expose the reason and the internal coding structure. Is there any way to let express jwt not to return response body without writing a middileware to clear it

**Comment by davebaol** [comment]
@XiSmartElf 
Sure, just use the standard [error handling](http://expressjs.com/en/guide/error-handling.html) technique provided by express.

Someone should close this issue :)

**Comment by cadrogui** [comment]
Hi, in this pr  [#126](https://github.com/auth0/express-jwt/pull/126) the feature has added.

regards.

**Comment by davebaol** [comment]
Ops looks like I missed the part "without writing a middleware to clear it".
I should have read more carefully, sorry.

**Comment by cadrogui** [comment]
extend its quite different from write a one, you should know it.

**Comment by rakesh1988** [comment]
I am adding middleware to handle JWT as below 
`app.use(jwt({secret: config.get('jwt.secret')}).unless({path: ['/store']}));`

and to handle error as below

```
app.use(function (err, req, res, next) {
    if (err.name === 'UnauthorizedError') {
        res.send(401, 'invalid token...');
    }
});
```
can you please help me understand why I still get a static HTML page with stack trace.

**Comment by rakesh1988** [comment]
my placement of the error handler was wrong :) ignore my prev comment

**Comment by jfromaniello** [comment]
You should use a proper error handling middleware.
