### ISSUE TITLE
JWT Permissions Middleware

### ISSUE THREAD

**Issue by MichielDeMey** [auth0/express-jwt#119]
Hey guys

We've written a super light-weight add-on middleware to check JWT tokens for certain permissions.
This middleware is actually written to be used in conjunction with this module, but can be freely used outside of it as well.

We've also made sure that we have ample tests, at least 100% code coverage and an easy-to-use API.

I'm leaving this here for anyone searching this repository on how to handle permissions.
Feel free to mention this in the README as well. 😃

https://github.com/MichielDeMey/express-jwt-permissions

**Comment by gastonelhordoy** [comment]
Hey @MichielDeMey, I just received the notification about your addition. Thanks for sharing it!

Now, it made me think if this would be a proper way to implement user authorization based on permissions.
How do you handle corner case scenarios where the list of permissions for a user has **very recently** changed but she got the token before that happened? Depending on how you deal with tokens, I guess you could invalidate the token and force the client to re-authenticate somehow. If you don't, then the user might have less permissions than she currently has, or which is worst, if permissions were revoked then she could still perform certain actions, right?

Thanks once again

**Comment by jfromaniello** [comment]
Good work! Can you send a PR adding a link to your project

**Comment by gillesdemey** [comment]
@gastonelhordoy You could check for invalidated tokens using the `isRevoked` callback function before passing the token to the `express-jwt-permissions` middleware, then simply revoke a token when the permissions have been altered.

Would that work for your use-case?

https://github.com/auth0/express-jwt#revoked-tokens

**Comment by MichielDeMey** [comment]
@jfromaniello https://github.com/auth0/express-jwt/pull/123 🎷🐢
