### ISSUE TITLE
Is this project considered dead?

### ISSUE THREAD

**Issue by btd** [auth0/express-jwt#122]
Hello, do not want to blame anyone, but last release was 6 month ago, according to npm. Last change in repo was 14 Jan. Can you consider adding collaborators to this project or become more active?

Thanks.

**Comment by jfromaniello** [comment]
No, is not considered dead. We use it a lot.

I don't follow your logic, but the frequency of the releases doesn't mean much.

Is there an issue that you would like to be addressed soon?

**Comment by btd** [comment]
> I don't follow your logic, but the frequency of the releases doesn't mean much.

IMHO repository considered healthy when issues and PR maintained at least (closed/answered/commented).

> Is there an issue that you would like to be addressed soon?

Most problem for me create outdated dependencies (lodash, jsonwebtoken at least)

**Comment by jfromaniello** [comment]
What problem does an oudated lodash create for you? npm can deal well with this

**Comment by jfromaniello** [comment]
I merged most of the PRs and closed one.. we are now using lodash.set

I will upgrade jwt soon.
