### ISSUE TITLE
Where jwt  tokens are stored?

### ISSUE THREAD

**Issue by ghost** [auth0/express-jwt#13]
Hello, sorry is it possible to know where JWT is actually storing the user token?

When a old token expires it gets automatically deleted (from where its stored) right?

THanks and sorry cause i'm lazy , for sure, but i tryed finding out where tokens are stored without any results :(

**Comment by lookforit** [comment]
One issue about security:
If the secret string in server side is revealed, some one can forge the fake token from the client side .This is spectrally dangerous if the decoded token include sensitive claim: role=admin eg.
Did I have the right understanding?

**Comment by jfromaniello** [comment]
@lookforit you are right about that. This is not an specific issue of JWT, the same happen with every other format of signed tokens
