### ISSUE TITLE
When JWT validated, the others app.use are not used

### ISSUE THREAD

**Issue by msepehr** [auth0/express-jwt#132]
Hi,

I'm quite new with express-jwt and NodeJS generally, so sorry it is a classical question (thought I did not find the answer in the forum!).
I've just implemented an API with NodeJS and secured it with Keycloak via JWT verification with using express-jwt which is a nice tool by the way!
I have a couple of Middleware functions using **app.use**, I've added some Log traces that illustrate that I pass through the handlers (never the JWT by the way) when the JWT is NOT correct. But when it IS valid, I do not pass through my handlers, by I go directly to the app.get() method.

```
// JWT verification
app.use(
	jwt(
		{ 
			secret: keycloakSecret, 
			algorithms: [ 'RS256' ] 
		} 
	), function (err, req, res, next) {
		console.log('-----LOG app.use jwt begin')
		next(err);
		console.log('-----LOG app.use jwt end')
	}
);
app.use(corsHandler);
app.use(headersHandler);
app.use(errorsHandler);

app.get(urlProducts,	
	function (req, res, next) {
		console.log('-----LOG app.get begin')
		if(res.statusCode >= 400) {
			return next();
		}
		var products = crm.getProducts();
		responseContent = { 'products': products, 'success': true, 'errors': [] };
		res.status(202).json(responseContent);
		log('INFO', req, res, responseContent);
		console.log('-----LOG app.get end')
		return next();
});
```

Cheers :)

**Comment by notredamstra** [comment]
Looking at the ExpressJS source code, specifically the route.js file, you can see how the `next()` function works.

```
function next(err) {
    if (err && err === 'route') {
      return done();
    }

    var layer = stack[idx++];
    if (!layer) {
      return done(err);
    }

    if (layer.method && layer.method !== method) {
      return next(err);
    }

    if (err) {
      layer.handle_error(err, req, res, next);
    } else {
      layer.handle_request(req, res, next);
    }
  }
```

I'm no expert myself, but I think using a parameter that is not 'route' means it's an error. Therefore the error handling is used instead of request handling. I suggest not using a parameter in your JWT middleware.

**Comment by msepehr** [comment]
Found some explanation:
My Middleware functions had this type of signatures:
corsHandler(err, req, res, next)
errorsHandler(err, req, res, next)
Appearently, this function with error (err) parameter is only used for ErrorHandling.
So I used it only errorHandler method:
```
corsHandler(req, res, next)
headersHandler(req, res, next)
errorsHandler(err, req, res, next)

```
But then the corsHandler and headersHandler were not called within errorsHandler, so I had to call it directly:
```
function errorsHandler(err, req, res, next) {
	console.log('-----LOG app.use Errors begin')
	try {
		corsHandler (req, res, function(){});
		headersHandler(req, res,  function(){});
```
Last thing to do was to exclude the error cases within the normal web services methods (app.get, etc.). Since I change the result statusCode, I check if it is in error, if so, I stop the process with next():
```
app.get(urlProducts, function (req, res, next) {
	console.log('-----LOG app.get begin')
	if(res.statusCode >= 400) {
		return next();
	}

```

**Comment by msepehr** [comment]
Last optimisation, I think this one is the best part :)
In my errorHandler, I used to finish the use cases with return next(err);
But by changing that to return; it just finishes the process without calling anyother further app methods.

```
function errorsHandler(err, req, res, next) {
	console.log('-----LOG app.use Errors begin')
	try {
		corsHandler (req, res, function(){});
		headersHandler(req, res,  function(){});
		
		// Error Handling
		if(err.status === 500) {
			console.log('-----LOG app.use Errors end1')
			return ;
		}

```	
app.get(urlProducts, function (req, res, next) {
    console.log('-----LOG app.get begin')
    ~~if(res.statusCode >= 400) {
        return next();
    }~~

So those technical codes are not intrusive. The business part of the API is not affected by that anymore!
