### ISSUE TITLE
credentialsRequired and expired tokens

### ISSUE THREAD

**Issue by IcanDivideBy0** [auth0/express-jwt#133]
Hello,
I'm building a react-native relay application.
I want to allow not logged in users to query the API. The authMiddleware from [react-relay-network-layer](https://github.com/nodkz/react-relay-network-layer) works great for my use case (with the `allowEmptyToken` flag to true), but the `refreshTokenPromise` never get called if i set `credentialsRequired` to false sever-side.

The `express-jwt` option `credentialsRequired` allow users without token to bypass the middleware, but it also let users with expired token to get in. I think it would be great if this option (or maybe add another one) can make a difference for expired tokens and no token.

I'm currently bypass this limitation by wrapping the middleware :
```js
const jwtMiddleware = expressJwt({
  secret: new Buffer(config.get('auth0:clientSecret'), 'base64'),
  audience: config.get('auth0:clientId'),
})

app.use((req, res, next) => {  
  if (!req.headers.authorization) return next()

  jwtMiddleware(req, res, next)
})
```
I know this isn't much code, and i can keep going this way, but I think the expired token behavior of `credentialsRequired` should at least be specified in the doc. Do you have any thoughts ?

**Comment by jfromaniello** [comment]
@IcanDivideBy0 Yes, you are absolutely. I will merge #127 and release a new major version.
