### ISSUE TITLE
How are you supposed to transfer the token to the client?

### ISSUE THREAD

**Issue by thelamborghinistory** [auth0/express-jwt#136]
I have a comprehension question: How are you supposed to pass a generated token from express to the client? Is that the point where you want to use `express-unless` for the route in which you pass the token in a json response or something like that?

Also, if you exclude your auth paths from this jwt middleware, how would you check if the user is already logged in if he tries to login again (okay, I guess in that case you would simply extend the token expiration date?) / to sign up with another user (that route would need an exclusion from the middleware, too, right?).

**Comment by jfromaniello** [comment]
This is well beyond the scope of this library.  The three scenarios I see are:

1.  The same api issues the token (as you described above).
2.  The client issues the token.
3.  A third party like google issues the token.

There are many ways to send a token to a client and back in the scenario 1. You might have an endpoint to exchange "credentials" (username&password, key id & key secret, etc) for a valid token. In that case this particular api will not require a token of course.
