### ISSUE TITLE
document breaking changes

### ISSUE THREAD

**Issue by mattkrick** [auth0/express-jwt#137]
I'm currently on v3.x.x and I see that v5.0.0 is now out. I don't see a migration doc anywhere in the readme or releases, so I assume that I can just bump the version, but usually a major version bump means a breaking change, so it'd be nice to see a little release note giving the reason for the major version bump.

**Comment by mpreziuso** [comment]
:+1: Also a nice History.md or a Changelog.md would be great

**Comment by kjanoudi** [comment]
If anyone is out there that has updated from 3.X.X to 5.0.0 and can tell us if there *are* breaking changes or not, please contribute here 👍

**Comment by jfromaniello** [comment]
from 3 to 5:

-  removed deprecate option `skip`.
-  fail if token is expired even if credentials is not required.

**Comment by kjanoudi** [comment]
Thanks!
