### ISSUE TITLE
requestProperty isn't available when req.body is not a valid JSON

### ISSUE THREAD

**Issue by joeltello** [auth0/express-jwt#138]
I was testing a protected endpoint and sent an `invalid JSON` in the `body` of a `POST` request by accident. Express' `body-parser` middleware by default discards the invalid body but it seems that `express-jwt` gets affected by this and doesn't append the `requestProperty` to the request object.

**Comment by joeltello** [comment]
Actually, it seems to be an issue with `body-parser` (I'm trying to fully understand what's going on).
I added this "error handler" 
```
app.use(bodyParser.json({ limit: '50mb' }))
app.use((err, req, res, next) => {
    // ignore invalid json objects as part of req.body
    next()
})
```

which seems to solve the issue...I would expect this to be the normal behavior

**Comment by jfromaniello** [comment]
I think is not related to this library.
