### ISSUE TITLE
Not properly checking expiration time

### ISSUE THREAD

**Issue by dat-leth** [auth0/express-jwt#14]
Express-JWT seems to not properly check the expiration time. Although the token is already expired and I checked it manually in the console, I still have access to the restricted endpoints.

Generating a token:

```
app.get('/authTest', function (req, res){
    genUuid = uuid.v4();
    token = jwt.sign({uuid: genUuid}, privateKey, {algorithm: 'RS256', expiresInMinutes: 5});
    res.json({token:token});
});
```

Router middleware to check the token:

```
router.use(expressJwt({secret: publicKey}));
```

**Comment by windmaomao** [comment]
i got same issue, the token is expired, I used the same way dat-leth to find out, but i still can use this token to access protected area. I'm using 0.6.2 for express-jwt and 3.2.0 for jsonwebtoken.

**Comment by windmaomao** [comment]
ok, my bad, it does check, and i need to get that info in app.use(function(err, req, res, next). I thought i'll get a 401 right away, but this is better. sorry about that.
