### ISSUE TITLE
Possible to verify tokens issued from Azure AD?

### ISSUE THREAD

**Issue by Lutando** [auth0/express-jwt#147]
Is it possible to verify issued tokens via Azure AD login?

Basically I am trying to protect all my endpoints but root on my node API

```
//aud and iss guids are fake for this post
server.use(jwt({
        audience: 'b4358ee7-c62a-48f5-a8f0-5175a0c4c785',
        issuer: 'https://sts.windows.net/81ed3d27-8ab3-4c8c-89c5-45962622af7f',
    }).unless({path : ['/']}))
```
My issuer has the appropriate discovery document at `{url}/.well-known/configuration`

**Comment by lyphtec** [comment]
Yes - use JWKS with the `jwks-rsa` module.  See Express sample [here](https://github.com/auth0/node-jwks-rsa/tree/master/examples/express-demo).

You just need to set the Uri to the JWKS endpoint.  This is available from the discovery document at the `jwks_uri` property. Default is something like https://login.microsoftonline.com/common/discovery/keys
