### ISSUE TITLE
Question: token

### ISSUE THREAD

**Issue by brackio** [auth0/express-jwt#153]
How do you get "admin" in the request user object (req.user.admin)?

**Comment by dcworldwide** [comment]
admin is a member of the JWT payload. It's custom, you must define within your JWT scope rules.

**Comment by brackio** [comment]
But how do you do that?(forgive my ignorance).

The reason I ask is because I am trying to protect my endpoints by verifying the request user has admin role.  Currently, all of the examples are only showing how to protect endpoints with logged in user.  I need both logged in & and has admin role.

**Comment by jfromaniello** [comment]
This middleware validates the signature of the JWT and puts the decoded payload in req.user or `requestProperty`. You can define your own middlewares after that validating any claims of the decoded payload.

> Currently, all of the examples are only showing how to protect endpoints..

The very first example in the readme show how to do this:

https://github.com/auth0/express-jwt#usage

One thing I use to do is this:

```
function requireAdmin(req,res,next) {
  if (!req.user.admin) { return res.send(401); }
  next();
}

//then in every endpoint:

app.get('/foo', requireAdmin, function(req,res,next){ ...});
app.get('/bar', requireAdmin, function(req,res,next){ ...});

//or just have a base path protected for admins like this. Every route starting with `/admin` will execute this middleware:
app.use('/admin', requireAdmin);
```
