### ISSUE TITLE
Custom User Object Shape

### ISSUE THREAD

**Issue by dcworldwide** [auth0/express-jwt#155]
Hi,

I'd like to transform the JWT payload before setting req.user. Is this possible?

I.e.

```
var authenticate = jwt({
    secret: new Buffer(process.env.AUTH0_SECRET, 'base64'),
    audience: process.env.AUTH0_CLIENT_ID,
    userTransform: (user) => new User(user)
});
```

This would be very useful if you wished to extend the user object with state and behaviour. I.e.

req.user.canUserRead(x) or req.user.hasRole("fdsfs")

**Comment by jfromaniello** [comment]
the way we usually do this is by using two middlewares:

```javascript
app.use(jwt({...});

app.use((req,res,next) => {
   req.user = new User(req.decodedToken);
   next();
});
```

feel free to open a PR if you consider this important.. I am not sure about `userTransform`. The decoded payload doesn't necessarily represents a user (yes, it was our mistake to user req.user at the beginning)

**Comment by dcworldwide** [comment]
I like your idea better. Works for me. Thanks @jfromaniello
