### ISSUE TITLE
JWT Encryption

### ISSUE THREAD

**Issue by fcpauldiaz** [auth0/express-jwt#160]
I want to encrypt the JWT but how can call my decrypt method before the express-jwt middleware.

For example I have this route
````javascript
router.route('/random-number')
  .get(expressJwt({ secret: config.jwtSecret }), authCtrl.getRandomNumber);
````

I need to decrypt before the jwt tries to parse the Bearer + token;
Is this possible?

**Comment by lazychino** [comment]
can do your decryption on some middleware before expressJwt like this

```js
function myDecryptMiddleware(req, res, next) {
  // decrypt token
  next()
}

router.route('/random-number')
  .get(myDecryptMiddleware, expressJwt({ secret: config.jwtSecret }), authCtrl.getRandomNumber);
```

**Comment by fcpauldiaz** [comment]
Thanks! @lazychino
