### ISSUE TITLE
Documentation: Options specification

### ISSUE THREAD

**Issue by dafranco** [auth0/express-jwt#169]
Hi! I was trying to specify the algorithm used to verify my signed token, to prevent
signature stripping attacks, but documentation does not talk about the options Object. I think that at least it must be specified that the options object is passed to 'jsonwebtoken' module at the time of verifying the token. I found the solution just looking at the code, but I think that it could be added to documentation to save time to users. (Sorry for my english)

**Comment by JayChandler** [comment]
Same here
