### ISSUE TITLE
new Buffer() deprecated since v6

### ISSUE THREAD

**Issue by dev101** [auth0/express-jwt#181]
Code sample of handling base64-encoded secret in [README](https://github.com/auth0/express-jwt/blob/master/README.md) triggers 
`new Buffer()' was deprecated since v6. Use 'Buffer.alloc()' or 'Buffer.from()' (use 'https://www.npmjs.com/package/safe-buffer' for '<4.5.0') instead` warning in my _standardjs_ linter.

I suggest you follow the advice and update the docs.

**Comment by Shyam-Chen** [comment]
#164
