### ISSUE TITLE
question: Custom error handler readme details

### ISSUE THREAD

**Issue by divyanshu013** [auth0/express-jwt#189]
Hi, thanks for this package! I've been trying to add a custom error handler following the readme guide:

```js
app.use(function (err, req, res, next) {
  if (err.name === 'UnauthorizedError') {
    res.status(401).send('invalid token...');
  }
});
```

I noticed that I was only able to make it work after adding this middleware after my routes. Maybe this should be mentioned in the readme? Or perhaps I'm missing something here about the usage. Here's how my main file looks like:

```js
// imports
...
const app = express();

// middlewares
app.use(cors());
app.use(morgan('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

// routes
app.use('/', something);
app.use('/else', else);
...

// where I add the custom handler
app.use((err, req, res) => {
	if (err.name === 'UnauthorizedError') {
		res.status(401).json({ message: 'Unauthorized. Invalid token!' });
	}
});

app.listen(8000, () => {
	console.log('Node middleware listening on port 8000!');
});
```

**Comment by ibc** [comment]
This is a Express core concept. The README of this library (`express-jwt`) cannot be a full Express tutorial:

http://expressjs.com/en/guide/error-handling.html

**Comment by divyanshu013** [comment]
Agreed it can't be a full express tutorial, (and neither is the issue about it to be one) but just a line mentioning **add this after your routes and other `app.use(...)` calls** would be helpful.

**Comment by timmushen** [comment]
This was helpful @divyanshu013  thank you!

**Comment by divyanshu013** [comment]
Awesome :)

**Comment by maestre3d** [comment]
Thanks guys, really helped me out without needing to modify the whole code.

**Comment by mikedehart** [comment]
I think what @ibc means is the issue has nothing to do with express-jwt. This would be common for any error handling in express.
Due to how middleware flow 'cascades' down, default error handling needs to occur after any defined routes where an error could occur.
