### ISSUE TITLE
Publish v5.3.1 to NPM

### ISSUE THREAD

**Issue by exactlyaron** [auth0/express-jwt#190]
Hi,

Would you be able to publish v5.3.1 to NPM, in order to fix [this vulnerability](https://snyk.io/test/npm/express-jwt/5.3.0?severity=high&severity=medium&severity=low) that has subsequently been fixed in v5.3.1 as jsonwebtoken has been updated to 8.1.0.

Thanks.  😃

**Comment by kyrylkov** [comment]
@jfromaniello @tjanczuk @ziluvatar Could you please address this?

**Comment by johncblandii** [comment]
Any chance this can get pushed to NPM?

**Comment by camsjams** [comment]
Also need this per same security issue mentioned by @exactlyaron, also seen on https://nodesecurity.io/advisories/566

**Comment by johncblandii** [comment]
Exactly why we need it, @camsjams.

**Comment by hzalaz** [comment]
Sorry guys, just pushed v5.3.1 to npm

**Comment by camsjams** [comment]
Wonderful, no worries and thank you!

**Comment by exactlyaron** [comment]
That's brilliant, thanks a lot @hzalaz very appreciated.  :+1:

**Comment by johncblandii** [comment]
Awesome, @hzalaz!
