### ISSUE TITLE
no error with .unless syntax

### ISSUE THREAD

**Issue by MeMeMax** [auth0/express-jwt#192]
Hi,
I am trying to protect all my routes except some which I specify in the .unless statement. Unfortunately nothing is protected. Is this a known problem?

```
app.use(expressJwt({
            secret: process.env.JWT_SECRET,
            credentialsRequired: false,
            requestProperty: 'auth',
            getToken: function fromHeader(req: express.Request) {
                if (req.headers.Authorization && (req.headers.Authorization as string).split(' ')[0] === 'Bearer') {
                    return (req.headers.Authorization as string).split(' ')[1];
                }
            }
        }).unless({path: ['/auth/login', '/auth/register', '/auth/activate']}));
```

**Comment by maljukan** [comment]
@MeMeMax I think this should be addressed to [express-unless](https://github.com/jfromaniello/express-unless/issues/18)  
The question for `express-jwt` maintainers should be: Is the code @MeMeMax referenced all it takes to make all routes protected or every single route must be also passed `jwt({secret: 'shhhhhhared-secret'})
`.  
It's unclear to me from the docs. If it's the case, why do we have `.unless()` if the mentioned midleware must be passed to all routes.

**Comment by maljukan** [comment]
Yep, i've checked and when i added jwt({secret: 'shhhhhared-secret'})`  as a second parameter of the route function everything works as expected. So this issue can be closed, sorry for not understanding the point of using both middlewares.
