### ISSUE TITLE
"TypeError: cb is not a function" when providing a native async function to options.secret 

### ISSUE THREAD

**Issue by KalleV** [auth0/express-jwt#202]
I narrowed it down to the "isFunction" check at: https://github.com/auth0/express-jwt/blob/master/lib/index.js#L10. Since the async function is not correctly recognized as a function (`Object.prototype.toString.call(object)` returns `[object AsyncFunction]`), the provided "secret" callback is wrapped by the default callback provided by "wrapStaticSecretInCallback".

The following `options.secret` function replicates the error:
```
async function secretProvider(req, header, payload, cb) {
   cb();
}
```

To fix the error, I would like to submit a PR to replace the isFunction check with the  https://www.npmjs.com/package/lodash.isfunction package which detects async functions.

**Comment by lukemcgregor** [comment]
Im not sure whats gone on here but this looks to have regressed?

https://github.com/auth0/express-jwt/blob/master/lib/index.js#L10

**Comment by pepoospina** [comment]
Hi @lukemcgregor, I wonder if this is a bug or not. Is there a simple way to go over it by changing the call to jwt.verify

**Comment by rebolyte** [comment]
@KalleV @jfromaniello I just got bitten by this as well. Could we get one of the open PRs merged?

**Comment by selvavalluvan** [comment]
@KalleV Any updates on this issue?

**Comment by Marcelo-Petrucelli** [comment]
I'm sorry to comeback to this guys. But I'm facing a weird behaviour related to this. I have something like this:

```
const CheckJwt = Jwt({
	secret: GetKey,
	audience: Env.JWT_AUDIENCE,
	issuer: Env.JWT_ISSUER,
	algorithms: ['RS256']
});
```

```
async function GetKey(req: Request, header: any, payload: any, done: (err: any, secret?: secretType) => void) { 
        //Stuff to get a key
        done(null, key);
}
```

I get as a result:
"TypeError: done is not a function"

From what I can tell:
"var arity = secretCallback.length;" is returning 3, instead of 4. 
I'd expect "isFunction(secretCallback)" to return true for my example and, for some reason it simply doesn't.

Am I doing something wrong here?
