### ISSUE TITLE
credentialRequired: false doesn't do anything when there is no token on request

### ISSUE THREAD

**Issue by viztor** [auth0/express-jwt#204]
I'm using it with GraphQL. so there is only one endpoint.

so when I set `credentialRequired:false`, user who haven't set a Authorization Header Bearer can not access the endpoint as the middleware will throw error when trying to read Authorization Header.

the error that got thrown is:
```
UnauthorizedError: Format is Authorization: Bearer [token]
```

in the RESTful world, we would be able to use `unless` to open access to public, but that is not possible with graphql.

so now I'm using a customized getToken function, as it was supplied on the website. and am hoping that set `credentialRequired: false` would be enough for that use-case rather than a customized getToken function.

**Comment by jacquesn** [comment]
I'm passing an empty string in as the Authorization header as @psaia suggests, but I do think it would be cleaner for `credentialsRequired: false` to allow access when Authorization is null.

**Comment by bombillazo** [comment]
It would be great if `credentialRequired: false` bypasses Auth validation even in Authorization header is set. What was the custom function used to bypass this? Unfortunately using a getFunction and returning `null` yields an error.

**Comment by jfromaniello** [comment]
I think the meaning of "credentialRequired: false" has always means do not fail if the token is not provided, but we always validate the token.

There are some examples using the `.unless` syntax here if you want to completely skip the middleware:

https://github.com/auth0/express-jwt#additional-options
