### ISSUE TITLE
credentialsRequired: false should call next without rejecting

### ISSUE THREAD

**Issue by AdityaAnand1** [auth0/express-jwt#231]
The `expressJwt` middleware seems to gobble up all requests that don't have a valid token:

![image](https://user-images.githubusercontent.com/13274079/86152101-4ee07500-bb1d-11ea-8405-e5f71376130d.png)

I'm just trying to attach a req.user if there is a token and do nothing if there isn't. I have same, similarly path-ed APIs being called on auth/non-auth flows so `.unless()` isn't usable. 

I couldn't find any other workaround as well, but I thought that credentialsRequired is exactly the solution, but it does not need to quietly call `next()` in the middleware.

Hence this issue:
1. What is happening? (maybe add a clearer description in readme?)
2. What's the solution?

**Comment by alexbrazier** [comment]
I think you just need to change your second function to:
```js
app.use((req, res, next) => {
 ...
})
```

By providing the `err` argument you are telling express to only call the function when there is an error.
