### ISSUE TITLE
Update the README to include the algorithms option now it is mandatory

### ISSUE THREAD

**Issue by Mozzius** [auth0/express-jwt#232]
## Describe the problem you'd like to have solved

If you follow the README's examples, they will not work in the current version of express-jwt since the `algorithms` option has been made mandatory. 

### Describe the ideal solution

Ideally the README should explain what the algorithms option does and what algorithms are available.

## Alternatives and current work-arounds

Just update the README to include a default algorithm so that the examples work i.e. HS256

### Additional context

I ran into this while updating the dependencies for a project and the README wasn't able to help me fix the problem. I had to search the repo for "algorithms" which is not ideal documentation :)

**Comment by TaylorDale** [comment]
Was getting very obscure errors in my env because of this change, had to step through into the jwt call to find out why.

**Comment by bit-cmdr** [comment]
Is this the breaking change from v5 to v6? I don't see any release notes or info in the CHANGELOG.

**Comment by soichih** [comment]
Is there a way to set the algorithm by default - so I don't have to update the entire App?

**Comment by soichih** [comment]
I just checked the code, and I can't think of anyway to set the default algorithm. This is not good. This update just broke a whole bunch fo Apps that uses expresss-jwt.

**Comment by Laoujin** [comment]
There is an open PR to fix this: https://github.com/auth0/express-jwt/pull/218

The new config would look like:
```
jwt({
  secret: 'shhhhhhared-secret',
  audience: 'http://myapi/protected',
  issuer: 'http://issuer',
  algorithms: ['RS256'],
})
```

RS256 is also what is currently being suggested by Github dependabot.

**Comment by evantaylor7** [comment]
I did this and got error 'invalid algorithms'

**Comment by 6footGeek** [comment]
Resolved by https://github.com/auth0/express-jwt/pull/234.
