### ISSUE TITLE
CHANGELOG out of date, does not reflect recent releases

### ISSUE THREAD

**Issue by grempe** [auth0/express-jwt#235]
The CHANGELOG file is not current with recent releases. There is a new `6.0.0` (major breaking semver) release that currently has no release note on the tagged release, and the CHANGELOG does not indicate the existence of this release.

The new version resolves a security issue and should be encouraged (and explained) to all users:

https://github.com/auth0/express-jwt/security/advisories/GHSA-6g6m-m6h5-w9gf

**Comment by twh1st** [comment]
I stumbled upon same issue. This is major release and no changelogs .. "no good, this is".

**Comment by lahdekorpi** [comment]
Is the breaking change that we need to specify `algorithms` each time? Ss suggested by commit https://github.com/auth0/express-jwt/commit/43b7921c2cb60d781655ac5527a8a47d9fb428fc .

**Comment by grempe** [comment]
cc: @mcastany who tagged the 6.0 release.
