### ISSUE TITLE
When a token is revoked the response is not in JSON format

### ISSUE THREAD

**Issue by carlocorradini** [auth0/express-jwt#243]
### Description

When a token is revoked the response from the server (GraphQL) is not in JSON format but instead in plain text.

### Reproduction

I'm developing a GraphQL server with JWT authentication token on some resolvers.
The middleware is working great blocking unauthorized requests and generating the correct response as a JSON message (This is shown in the image below).

![immagine_2020-10-13_115128](https://user-images.githubusercontent.com/21266147/95845417-6cdb8980-0d4a-11eb-960d-ca00be9c5ae8.png)

#### The problem
However when using the ```isRevoked``` function and the token is revoked, the error message is directly write to the console and the response from the server doesn't contain any JSON but the error message in textual format instead.
When a token is **not revoked** the server/middlewares responses **works as expected.**

##### express-jwt configuration
```typescript
app.use(
        '/graphql',
        jwt({
          secret: config.JWT.SECRET,
          algorithms: ['HS256'],
          credentialsRequired: false,
          isRevoked: async (req, _, done) => {
            const token: string | undefined = JWTHelper.getToken(req);

            if (!token || (await JWTHelper.isBlocked(token))) {
              return done(new UnauthorizedError('The JWT token has been revoked'), true);
            }

            return done(undefined, false);
          },
        }),
      );
```

##### Response as plain text
```
UnauthorizedError: The JWT token has been revoked
    at isRevoked (C:\graphql\src\server\Server.ts:77:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

##### GraphQL playground error
Consequently, the GraphQL playground generate an error that represents JSON parsing failure.

![immagine_2020-10-13_120953](https://user-images.githubusercontent.com/21266147/95847437-0015be80-0d4d-11eb-8684-84cbc621d72d.png)

### Environment

- **Version of this library used:** 6.0.0
- **Version of the platform or framework used, if applicable:** apollo-server-express v. 2.18.2 + express v. 4.17.1
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:** type-graphql v. 1.0.0

**Comment by douglascayers** [comment]
You may need to add an express error handler to do something with the rejection error.

https://expressjs.com/en/guide/error-handling.html

Example:
```js
app.use(function (err, req, res, next) {
  console.error(err.stack)
  // Return the error however you'd like
  res.status(500).send('Something broke!')
})
```
