### ISSUE TITLE
exclusion route

### ISSUE THREAD

**Issue by angelochen960** [auth0/express-jwt#27]
Hi,
got this :app.use('/api', expressJwt({secret: '123'}).unless({path:['/get_price']}));
api is protected, but api/get_price allows un protected access, I did a test, but still get 401:

```
curl -i -k https://localhost:3000/api/get_price/01
HTTP/1.1 401 Unauthorized
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 77
ETag: W/"4d-118870433"
Date: Sun, 31 Aug 2014 11:15:49 GMT
Connection: keep-alive

<h1>No Authorization header was found</h1>
<h2>401</h2>
<pre>undefined</pre>
```

why?

**Comment by noorahmed94** [comment]
@jfromaniello  I have a route like " courses/download/:filename" , I want this download route to be excluded from jwt authentication and i am using `app.use(expressJWT({ secret: "APP_SECRET" }).unless({ path: ['/authenticate', '/courses/download/'] }));` but its not working
