### ISSUE TITLE
Upgrade to async 3.2.2+?

### ISSUE THREAD

**Issue by birdsarah** [auth0/express-jwt#278]
Got this security warning as a dependency of express-jwt.

https://github.com/advisories/GHSA-fwr7-v2mv-hh25

Is it possible to upgrade and publish a new package?

**Comment by icey-franken** [comment]
bump

**Comment by birdsarah** [comment]
bot pr #276

**Comment by talaltoukan** [comment]
bump

**Comment by jfromaniello** [comment]
asyc is not longer a dependency in v7
