### ISSUE TITLE
Integration with jwks-rsa is broken when moving from 6.1.2 to 7.4.2 breaks

### ISSUE THREAD

**Issue by nsshunt** [auth0/express-jwt#282]
Linked to a previously closed issue (#281), the integration with jwks-rsa to this module no longer works.

https://github.com/auth0/express-jwt/issues/281

The issue has also been noted within the jwks-rsa repo as well.

See issue #281 for more details.

**Comment by gtwilliams03** [comment]
I also think this might have broken `jsonwebtoken` - as soon as I upgraded to `v7.4.2` I couldn't use that package anymore.

**Comment by gtwilliams03** [comment]
Rolling this package back to `6.1.2`.

**Comment by kevinrutherford** [comment]
+1, had to roll back

**Comment by jfromaniello** [comment]
for reference, this PR should fix the issue:

https://github.com/auth0/node-jwks-rsa/pull/297

**Comment by jfromaniello** [comment]
Fixed in jwks-rsa@2.1
