### ISSUE TITLE
Document breaking changes in v7

### ISSUE THREAD

**Issue by mirkonasato** [auth0/express-jwt#283]
Would be nice to have some instructions on how to upgrade from v6 to v7 in either the README or Changelog. The Changelog only mentions

>  Convert the project to typescript and improve typescript

which I took to mean it was an internal rewrite, with no breaking changes.

But as far as I can tell there at least these two major changes that require users to modify their code:

1. The middleware function is now available as a named import rather than a default one: `import { expressjwt } from 'express-jwt'`
2. The decoded JWT payload is now available as `req.auth` rather than `req.user`

**Comment by KillerCodeMonkey** [comment]
setting `requestProperty` is not available any more
and the interface for `TokenGetter` is not exported

**Comment by felixmosh** [comment]
`isRevoked` interface was changed, it passes the entire jwt instead of the payload only in the second argument, and there is no `done` as 3rd argument.

**Comment by LebonNic** [comment]
It would be nice if we could choose the name of the property that is used to store the token. For my part, the name `auth` is already used by another library which sets this value in the `req` object... So I have a collision between the two libraries and I can't update `express-jwt`.

**Comment by jfromaniello** [comment]
-  documented the changes here https://github.com/auth0/express-jwt#migration-from-v6
-  TokenGetter is now exported
-  put back the `requestProperty` parameter
-  documented the entire api here https://github.com/auth0/express-jwt#api

**Comment by boobo94** [comment]
Cannot set nested objects anymore using `requestProperty`, it was working in ` "express-jwt": "^6.1.1",`.

Using `"express-jwt": "^8.2.1",` with `requestProperty: 'payload.user',`  it does the following:


```js
req: {
...
  payload: {
    foo: "bar"
  },
  "payload.user": object // the payload of token

...
}
```

**Comment by jfromaniello** [comment]
@boobo94 thank you for reporting this, I've reverted to the previous behavior in `v8.3.0`.

**Comment by boobo94** [comment]
> @boobo94 thank you for reporting this, I've reverted to the previous behavior in `v8.3.0`.

everything works great. thanks for your help <3
