### ISSUE TITLE
Wrong typing for algorithms

### ISSUE THREAD

**Issue by fsanzv** [auth0/express-jwt#285]
### Description

If you do not provide ´algorithms´ option you get an exception in run time.

I know this is in the doc: https://github.com/auth0/express-jwt#required-parameters but the typings used for ´algorithms´ option comes from jsonwebtoken package and there the ´algorithms´ is defined as optional.

I think this typing should be overridden in jwt to avoid confusion.

**Comment by jfromaniello** [comment]
good catch! fixed in v7.6.1
