### ISSUE TITLE
Type 'SecretCallbackLong' is not assignable to type 'GetVerificationKey'.

### ISSUE THREAD

**Issue by ValchanOficial** [auth0/express-jwt#288]
express-jwt version: 7.6.0
jwks-rsa version: 2.1.1

Before express-jwt update, this code was working
Old version: 6.1.1

![image](https://user-images.githubusercontent.com/16228014/167650182-eae9e7fb-4f67-4365-bcf2-cc232a94c62e.png)

Could you help me? Thank you in advance!!

**Comment by jfromaniello** [comment]
ouch! we have tried so many times to fix this issue 😖 

The newest version of jwks-rsa is compatible with the express-jwt but there is an issue with the typings.

Can you use `as GetVerificationKey` for the time being as follows:

```ts
import { expressjwt, GetVerificationKey } from 'express-jwt';
import { expressJwtSecret } from 'jwks-rsa';


expressjwt({
  secret: expressJwtSecret({
    jwksUri: 'https://foobar.com'
  }) as GetVerificationKey,
  algorithms: ['RS512']
});


```

**Comment by Sti2nd** [comment]
Would be great if the typings were consistent with each other, but good to know that they are supposed to work together. Then it feels safer to cast.

**Comment by jfromaniello** [comment]
@Sti2nd thanks for the feedback, I think this should fix it https://github.com/auth0/node-jwks-rsa/pull/412

**Comment by rmlevangelio** [comment]
@jfromaniello the fix didn't make it to npm?
