### ISSUE TITLE
Nestjs error TS2349: This expression is not callable.  jwt

### ISSUE THREAD

**Issue by evographics** [auth0/express-jwt#293]
### Description

Following the tutorial https://www.youtube.com/watch?v=JzndSOAb6SQ from scratch, there is an error in the latest version 7.7.2. 

![image](https://user-images.githubusercontent.com/72199827/169494626-944aeb09-eae4-4f19-ae03-3f9ac8c86163.png)

### Reproduction

1. Download the repo https://github.com/Sambego/nestjs-auth0-api
2. Run `yarn` to install everything
3. Run `yarn upgrade --latest` to upgrade all the packages 
4. Run `yarn start:dev`

You can see the error lint in VSCode as well in the authorization guard file.

![image](https://user-images.githubusercontent.com/72199827/169495160-568df202-5bfc-4603-848d-9be871ec7760.png)

### Environment

> Please provide the following:

- **Version of this library used:*7.7.2*
- **Version of the platform or framework used, if applicable: *NestJS 8*
- **Other relevant versions (language, server software, OS, browser):*TypeScript*
- **Other modules/plugins/libraries that might be involved:*jwks-rsa*

**Comment by jfromaniello** [comment]
Hi there, unfortunately the youtube tutorial is using express-jwt@6. This is what you will need to do in your example to use express-jwt@7:

https://github.com/Sambego/nestjs-auth0-api/pull/2

**Comment by dioggosoares** [comment]
just express-jwt@6.1.2 work for me

**Comment by evographics** [comment]
Thank you. @jfromaniello
