### ISSUE TITLE
Express-JWT 7.x Typescript+Express Typing issues

### ISSUE THREAD

**Issue by dfellis** [auth0/express-jwt#298]
### Description

I have followed the type overriding [to integrate `express-jwt` and `jwks-rsa`](https://github.com/auth0/express-jwt/issues/288) but the [Typescript Express instructions](https://github.com/auth0/express-jwt#typescript) do not work for me.

When I use the provided `Request` type from `express-jwt`, I receive the following error from the Typescript compiler:

```
src/router/db.ts:66:20 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '(req: Request, res: express.Response) => Promise<express.Response<any, Record<string, any>> | undefined>' is not assignable to parameter of type 'Application<Record<string, any>>'.
      Type '(req: Request, res: Response<any, Record<string, any>>) => Promise<Response<any, Record<string, any>> | undefined>' is missing the following properties from type 'Application<Record<string, any>>': init, defaultConfiguration, engine, set, and 61 more.

66 db.post('/export', async (req: Request, res: express.Response) => {
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/express-serve-static-core/index.d.ts:174:5
    174     (path: PathParams, subApplication: Application): T;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The last overload is declared here.
```

### Reproduction

I suspect it is due to the difference in how we attach express-jwt to our endpoints. As we apply it to nearly all endpoints in our application if auth is enabled by the user, we placed it in [an express `use` function](https://github.com/iasql/iasql-engine/blob/main/src/router/index.ts#L15-L25) to be executed on all of our `/v1/` endpoints. The complaint happens in a sub-Express object that has been converted, in this case a `POST` endpoint on `/v1/db/export`.

I expect that the `req` variable is still being mutated correctly in v7.x, but the type is getting erased and returned back to the standard `express.Request` type. [The `@types/express-jwt` package for 6.x](https://www.npmjs.com/package/@types/express-jwt) simply mutates the global type space for Express adding an interface also named `Request` that contains an optional `user` property of an opaque `User` interface type.

This may be a solution here, or it may be too heavy-handed for you, but I wanted to bring it up if you can't find a proper solution to the apparent type erasure problem.

### Environment

> Please provide the following:

- **Version of this library used:** `express-jwt@7.7.5`
- **Version of the platform or framework used, if applicable:** `Node v16.15.0`, `Express v4.18.1`, `Typescript v4.7.3`
- **Other relevant versions (language, server software, OS, browser):** Reproducible across multiple OSes, but I am on Ubuntu 22.04.
- **Other modules/plugins/libraries that might be involved:** I am pretty sure I covered them all above.

**Comment by jfromaniello** [comment]
We didn't want to polute the Request object globally in this release as this also generates some problems. 

I am not sure what's the definition of your `db.post` or where does this comes from. Maybe if you give me more details about this I can propose other solutions.

If it is fine for you, you can extend express Request globally in your project. 

Another option is to cast the object to expressJwt.Request  as in `const auth = (req as expressJwt.Request).auth` instead of changing the signature of the handler

**Comment by Kal-Aster** [comment]
I actually encountered this same problem.
I get it tring to use the expressjwt handler on a router.

To reproduce it's simple as:
```ts
import { Router } from "express";
import { expressjwt } from "express-jwt";

Router().use(expressjwt({}));
```

I get this error:
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ (req: Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>, res: Response<any, Record<string, any>>, next: NextFunction): Promise<...>; unless: (options: Params) => { ...; }; }' is not assignable to parameter of type 'PathParams'.ts(2769)
```

VScode points out:  
`@types\express-serve-static-core\index.d.ts(153, 5): The last overload is declared here.`

**Comment by jfromaniello** [comment]
hey @Kal-Aster , I think I found the issue. Would you mind to try v8.5 on npm?

**Comment by Kal-Aster** [comment]
Sure, let me know when it's published

**Comment by jfromaniello** [comment]
Sorry, published!

**Comment by hongbo-miao** [comment]
I can confirm it [works well](https://github.com/hongbo-miao/hongbomiao.com/pull/21410/files) now with express v5, thank you! 😃
