### ISSUE TITLE
Access token without the Authorization header (cookie?)

### ISSUE THREAD

**Issue by jitowix** [auth0/express-jwt#30]
I'm in a situation where I need to access req.user without the authorization header being set.
Let's say a user directly go to this path: `/test` (for example after a callback)
I need to be able to authenticate the user in the route:

    app.route('/test')
      .get(function (req, res) {
        // No authorization header, no req.user :(
      });

What I'm doing at the moment is manually set the header by reading the token from a cookie like this:

    function setHeader(req, res, next) {
      if(req.cookies && req.cookies.hasOwnProperty('token')) {
        // Copy the token without the quotes
        req.headers.authorization = 'Bearer ' + req.cookies.token.slice(1, req.cookies.token.length -1);
      }
      next();
    }

Is there a better solution or am I doing something wrong?

**Comment by jfromaniello** [comment]
Now you can use `getToken: function (req) { return req.cookie('xyz'); }`

**Comment by sirius1024** [comment]
Not sure the old API of express but for now(4.16.3) the getToken function should be: 
```js
(req)=>{ return req.cookies.xyz }
```
BTW, app.use(jwt(...)) should after app use cookie-parser middleware.
