### ISSUE TITLE
ES6 Import Not Working

### ISSUE THREAD

**Issue by Tarekrahman5500** [auth0/express-jwt#302]
import {expressjwt} from "express-jwt";

// create function that prevent un auth login to access the api
```
function authJwt() {
    const secret = process.env.SECRET_KEY;
    const api = process.env.API_URL;
    return expressjwt({
        secret,
        algorithms: ['HS256']

    }).unless({
        path: [
            'api/v1/users/login'
        ]
    })
}
module.exports = authJwt
```
when use 
```
var { expressjwt: jwt } = require("express-jwt");
 return jwt({))
```
work fine but i need in es6
the code work fine when not use es6 import style
express-jwt": "^7.7.5
xpress": "^4.18.1
node-16.15
os-windows 11

**Comment by SteveSuv** [comment]
https://www.npmjs.com/package/@types/express-jwt

**Comment by trasherdk** [comment]
![image](https://user-images.githubusercontent.com/5003891/203554523-d12a3198-da0e-457e-8bcb-57d515f91de5.png)

**Comment by jfromaniello** [comment]
What is the error you get? 

Btw you don’t need @types/express-jwt anymore. Newer versions include the types
