### ISSUE TITLE
Remove `@types/express-unless` from deps of `@types/express-jwt`

### ISSUE THREAD

**Issue by xinghul** [auth0/express-jwt#307]
Hello, I hit this error earlier:
```bash
error TS2688: Cannot find type definition file for 'express-unless'.
  The file is in the program because:
    Entry point for implicit type library 'express-unless'
```

I think there are two issues here:

1. first of all, `jwks-rsa` listed `@types/express-jwt` as part of its dependencies, which is wrong IMO. (types definitions should be devDependencies instead, unless it's for another types definition.)
2. starting from `v2.0`, `@types/express-unless` is just a stub types definition, `express-unless` comes with it's own typing, so `@types/express-jwt` should remove it from it's deps.

fixing no.2 should fix the issue.

**Comment by jfromaniello** [comment]
Thank you, fixed in express-jwt@7.7.7
