### ISSUE TITLE
Why does express-jwt no longer use the extended express.Request ?

### ISSUE THREAD

**Issue by stegano** [auth0/express-jwt#311]
### Description
Exteneded `express.Request` were available in `express-jwt` 6.x versions, but no longer available in `express-jwt` 7.x versions. Why does `express-jwt` no longer use the extended `express.Request`? I'm curious what the reason is.
The Request type provided by `express-jwt` 7.x cannot pass express.Request generic, making it difficult to use..
Please let me know if I'm misunderstanding anything. Thank you in advance.

### Environment
- express-jwt 7.x

**Comment by jfromaniello** [comment]
We consider better to not pollute the express Request type. 

You can get the previous behavior in your project by creating a file `src/types/express/index.d.ts`:

```ts
import * as jwt from 'jsonwebtoken';

export {}

declare global {
  namespace Express {
    export interface Request {
      auth: jwt.JwtPayload;
    }
  }
}
```

**Comment by stegano** [comment]
@jfromaniello Thanks for your reply. 😀
