### ISSUE TITLE
Upgrade jsonwebtoken library

### ISSUE THREAD

**Issue by aliosmanisikk** [auth0/express-jwt#312]
### Description

`jsonwebtoken` 8.5.1 has security vulnerability https://github.com/advisories/GHSA-27h2-hvpr-p74q and needs an upgrade to version `9.0.0`

**Comment by bfxavier** [comment]
Given the seriousness of the vulnerability, upgrading to 9.0.0 should be top priority.

**Comment by jfromaniello** [comment]
Published as express-jwt@8... no other breaking changes in this new release.
Updated changelog.
