### ISSUE TITLE
Use something like req.tokenPayload instead of req.user

### ISSUE THREAD

**Issue by aaronshaf** [auth0/express-jwt#41]
After all, the token payload itself may contain user information that we may want to put directly on `req.user`.

**Comment by jfromaniello** [comment]
I agree, I think "decodeToken" will be a better name. You can do this now with  `userProperty: 'tokenPayload'`, I don't like userProperty either

**Comment by jfromaniello** [comment]
in addition to `userProperty`, v1.1.0 support `requestProperty: 'decodedToken'`.

The default value is still user.
