### ISSUE TITLE
Unnecessary and confusing UnauthorizedError output to console

### ISSUE THREAD

**Issue by dineshdh** [auth0/express-jwt#44]
I have express app with a simple express-jwt implementation. Everything functions fine, however the  console shows `UnauthorizedError: No Authorization header was found` when accessing url paths that are in the `.unless(path[..])` array. The response is 200 OK which is what I want, however I think it's really misleading to show UnauthorizedError on the console. Can we please update express-jwt to suppress this message if the path is defined in unless.

I can get around this by creating my own error handler (see below), but I believe I shouldn't have to do this

```
app.use(function (err, req, res, next) {
    if (err.name === 'UnauthorizedError') {
        res.send(401, 'invalid token...');
    }
});
```

**Comment by jfromaniello** [comment]
@kentcdodds thanks for the feedback.

You can also use `app.use(express.favicon())`.

Most of the time you use this middleware for APIs, not for browser content. 

Thanks for reporting but we are not going to hardcode this ignore.
