### ISSUE TITLE
credentialsRequired is required for the middleware to work

### ISSUE THREAD

**Issue by wiggin** [auth0/express-jwt#46]
I'm not sure if this is intentional or not, but with the merge of pull request 68189c12fb2d0ff084f71ae7e83417ea39e3530f you have to specify the option ```credentialsRequired: true``` for the middleware to work, otherwise it will skip validation of the jwt. 

If this is expected behaviour if would be good if the readme was updated since it took me a while before I figured out why the middleware wasn't throwing an error as I expected.

**Comment by jfromaniello** [comment]
I'm sorry, definitely not the expected behavior. 

I have unpublished `v0.6.0` and published `v0.6.1` fixing the issue.

**Comment by wiggin** [comment]
Thanks for fixing it so quick and nice with the additional unit test :)
