### ISSUE TITLE
"undefined is not a function" on jwt.sign

### ISSUE THREAD

**Issue by OKNoah** [auth0/express-jwt#48]
Code:

	jwt = require('express-jwt'),
	var token = jwt.sign( { id: user._id }, secret.secretToken, { expireInMinutes: tokenManager.TOKEN_EXPIRATION } )

Error:

			var token = jwt.sign( { id: user._id }, secret.secretToken, { expireInMinut
			                ^
    TypeError: undefined is not a function

**Comment by jfromaniello** [comment]
This module is used only to validate/decode jwts on express.js requests.

If you need to sign requests you need to use https://github.com/auth0/node-jsonwebtoken

If there is a bit of documentation causing this confusion, please feel free to submit a pr.

**Comment by subpopular** [comment]
Seems you could just as easily export the sign method from the already included jsonwebtoken module so that this module could provide that, no?

**Comment by cgarvis** [comment]
+1

**Comment by liam-betsworth-leadin** [comment]
+1

**Comment by acushlakoncept** [comment]
This fix the issue for me.
`const { expressjwt: jwt } = require("express-jwt");`

**Comment by jaerperez** [comment]
thanks @acushlakoncept great solution! it's working for me

**Comment by Benja1512** [comment]
+1

**Comment by Jay-study-nildana** [comment]
@acushlakoncept 

This fixes my issue as well, but, why is this not already in the documentation :(
