### ISSUE TITLE
No wildcard unless?

### ISSUE THREAD

**Issue by geoguide** [auth0/express-jwt#53]
I can't seem to do app.use('/api', expressJwt({secret: secret}).unless({path: ['/api/public/*']}));

It seems like I should be able to, but it is not working. I have to specify each individual public route.

**Comment by Prophet32j** [comment]
try with regular expression.
path: /\/api\/public/i

it should allow all /api/public calls through.

**Comment by jfromaniello** [comment]
yes, as @Prophet32j  said, regex is the way to go:

```javascript
app.use('/api', expressJwt({secret: secret}).unless({path: /\/api\/public/i }));
```

**Comment by geoguide** [comment]
Thanks!

**Comment by kurorido** [comment]
That's not work for me,

I find the code in express-unless/lib/index.js check the instanceof RegExp which will never be true.
`var ret = (typeof p === 'string' && p === url) || (p instanceof RegExp && !!p.exec(url));`

so I use following instead.
`app.use('/api', expressJwt({secret: secret}).unless({path: new` RegExp('/api\/public.*/', 'i') }));

**Comment by ajbraus** [comment]
This did not work for me either. Shouldn't there be a simple solution for RESTful routes?


These two work
GET /users - allowed
POST /users - not allowed

but this one there is no solution for?
GET /users/:id - allowed

**Comment by ajbraus** [comment]
This just doesn't work for common RESTful paths you want to protect.

**Comment by rclai** [comment]
Guys, you can do this:

```
router.use(
  jwtExpress({ secret: JWT_SECRET }).unless({
    path: [
      '/static-route1',
      '/static-route-2',
      /^\/dynamic-route\//,
    ],
  })
);
```

**Comment by vemuez** [comment]
You can also just write `new RegExp('/api/public', 'i')`, it produces the same result as @jfromaniello's solution.
