### ISSUE TITLE
UnauthorizedError even when authorized

### ISSUE THREAD

**Issue by james-gardner** [auth0/express-jwt#54]
Hi,

I've got everything working and my application is successfully reading tokens. A passing curiosity however is when I use the following:

    app.use(expressJwt({secret : 'secret'}).unless({ path : ['/user/auth']}));

And afterwards have an error handler like this:

    app.use(function (err, req, res, next) {
        console.log(err);
    });

UnathorizedError is always being thrown. 

I did a little digging around in the source and it looks like two calls are being made in succession to middleware. The first is successful and the token is found but subsequently another is made and the 'token' variable never gets set.

Is this a rookie mistake I'm making within my express app? I think that's likely but it'd be good to get some clarity on this for myself and anyone else working with this awesome library.

Note: I'm using Express 4.x - Only happens on Chrome.

**Comment by terencemutizwa** [comment]
Having similar issue, the 'credentialsRequired:false' seems to work but obviously might be letting everyone through, even unauthorized, 

``` 
   app.use(jwt({
    secret: 'hello world !',
    credentialsRequired: false
    }));
```
It's really confusing because one of my urls is let through fine but not the others ones. That plus lack of parameterized urls got me thinking of trying sothng else

**Comment by jfromaniello** [comment]
@james-gardner You can try with this:

```javascript
app.use(function (err, req, res, next) {
    console.log(err.message, req.originalUrl);
});
```

If your web application is being used within a browser, chances are that favicon.ico is being hit. By loggin the originalUrl you will discover what's going on.
