### ISSUE TITLE
Is this project actively maintained?

### ISSUE THREAD

**Issue by demisx** [auth0/express-jwt#58]
I see the build is failing and no responses to latest issues. Currently, evaluating JWT libs for node. Thank you.

**Comment by jfromaniello** [comment]
> Is this project actively maintained?

Yes

> I see the build is failing and no responses to latest issues

Yes, the build was broken in travis-ci for 0.8 and I've fixed in  69cb5f71d8b268441b7ce17d4f50f3f8d4049d70
