### ISSUE TITLE
Set the decoded JSON object to req.payload

### ISSUE THREAD

**Issue by julientherier** [auth0/express-jwt#63]
As the decoded object is the entire payload, would it make sense to assign this to ````req.payload```` and let the app finds the user itself and then assigns it to ````req.user````?
I know we can also do ````jwt({ secret: 'shhhhh', requestProperty: 'payload' });````.

**Comment by vlapo** [comment]
I have problem with this right now. My jwt payload containst only userId, but I need user object from mongodb in ```req.user```.

```
jwt({ 
    secret: 'shhhhhhared-secret',
    decodeUser: function( payload ) {
          //find user in db by payload
          var user = .....
          return user;
    }
})
```

**Comment by jfromaniello** [comment]
@vlapo you solve this with another middleware

```javascript
app.use(jwt({ secret: 'shhhhh', requestProperty: 'token' }));
app.use(function (req, res, next) {
  users.get(req.token.user_id, function (err, user) {
    if (err) return next(err);
    req.user = user;
    next();
  });
});
```

**Comment by jfromaniello** [comment]
@julientherier I don't like `user`, but I don't like `payload` either. 

I think `token`, `tokenPayload`, `decodedToken` are better options

**Comment by vlapo** [comment]
@jfromaniello I know and thnx :) But I think new options with decode token to ```req.user``` is very usefull and make express-jwt more complex.
