### ISSUE TITLE
x-access-token for the JWT token

### ISSUE THREAD

**Issue by julientherier** [auth0/express-jwt#64]
I use ````Authorization```` HTTP header for basic authentication mainly. Wouldn't be better to use ````x-access-token```` HTTP header to share JWT token?

Even if possible to do:
```
app.use(jwt({
  secret: ’shhhhht',
  getToken: function(req) {
    if (req.headers && req.headers['x-access-token']) {
      return req.headers['x-access-token'];
    }
    return null;
  }
}));
```

**Comment by sokardys** [comment]
+1

**Comment by jfromaniello** [comment]
Sorry for the delay. It seems we support this exact API since some time ago.
