### ISSUE TITLE
credentialsRequired and the setting of request.user on failed verification?

### ISSUE THREAD

**Issue by jasonkenneth** [auth0/express-jwt#66]
I have a use case where I do not want to requireCredentials but I still want to populate request.user if given a *valid* credential. 

Currently, even if verify fails, the express-jwt request handler still sets request.user.
https://github.com/auth0/express-jwt/blob/master/lib/index.js#L104

**Comment by jfromaniello** [comment]
Sorry for the delay, I think this is not longer the case, can you confirm?
