### ISSUE TITLE
bower version of express-jwt using jsonwebtokens@4.2.2 which has a vulnerability.

### ISSUE THREAD

**Issue by johnwebbcole** [auth0/express-jwt#69]
The package.json file and the bower version of express-jwt are using `jsonwebtokens` version 4.2.2.  According to the [auth0 blog](https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/) there is a vulnerability in this version and it should use v5.0.0 instead.

**Comment by jfromaniello** [comment]
That's incorrect. This library was fixed before the blogpost and 4.2.2 is not vulnerable. Check the changelog and commits:

https://github.com/auth0/node-jsonwebtoken/blob/master/CHANGELOG.md#422---2015-03-26

4.2.2 verifies the `alg` field even if the jws dependency doesn't. 
5.0.0 updates to the latest version of jws which also checks the alg field.

I don't understand why would you use this library with bower

**Comment by pose** [comment]
@johnwebbcole Sorry, it was an issue on our side. This is what happened:

Versions `>= 4.2.2` of `node-jsonwebtoken` are safe to use but we decided to deprecate everything `< 5.0.0` to prevent security warnings from library `node-jws` when doing `npm install`. Although `node-jws` reports that `4.2.2` is vulnerable, it is not. The algorithm checks are done from `node-jsonwebtoken` side before invoking `node-jws`. But, as we wanted to not worry our users with that warning, we decided to release a `5.0.0` version that contains the latest `node-jws` library version (`^3.0.0`). Hope that helps to understand the error. Now if you install, `express@3.0.0` you should not be getting any errors. Please re-open this issue if that's not the case.

Thanks in advance!
