### ISSUE TITLE
Unless `path` should be improved

### ISSUE THREAD

**Issue by grabbou** [auth0/express-jwt#71]
When subapp is being used like so:

```js
// main.js
var main = express();
var api = require('./api');
main.use('/v1', api);

// api.js
var api = express();
api.use(jwt({...}).unless({path:['/auth/login']});

module.exports = api;
```
It won't work as long as you prefix `auth/login` with `v1` which makes the whole idea of subapping a bit pointless. As long as it is a middleware, it should be able to take profit from `mountpath` to prepend the routes, shouldn't it?

**Comment by grabbou** [comment]
Ok, closing it as I've discovered you are depending on an external lib.

**Comment by jfromaniello** [comment]
Yes, i think is confusing, but is a breaking change so I might change this
on a future major version.
