### ISSUE TITLE
Misleading revoke section in the README

### ISSUE THREAD

**Issue by givanse** [auth0/express-jwt#77]
In the revoke section says:

> For example, if the (iss, jti) claim pair is used to identify a JWT:

In https://github.com/auth0/node-jsonwebtoken/issues/36 it says:

> ...tokens return by Auth0 currently (we are thinking abut adding it in the future) don't return a jti...

Also, in the code sample this are lines are shown but they don't seem to point to any code/library that supports them.

    var data = require('./data');
    ...
    data.getRevokedToken(issuer, tokenId, function(err, token){

So, revoke functionality needs to be implemented pretty much from scratch, right?

**Comment by nathanielaozl** [comment]
Id you get an answer/response for this over at ask.auth0.com?

**Comment by givanse** [comment]
I never asked there. I'm pretty sure the revoke/invalidate functionality is left to be done by your own. There are more than a couple of way of doing it and it seems like we don't have a consensus for the best approach yet.

**Comment by nathanielaozl** [comment]
Use express-jwt if you're using express.
