### ISSUE TITLE
Using unless path with HTTP Methods

### ISSUE THREAD

**Issue by alanjames1987** [auth0/express-jwt#80]
How does one go about using the `.unless` function passing a path array while also specifying http methods?

I want restrict POST requests to certain routes but not GET requests.

**Comment by alanjames1987** [comment]
After looking at the code I see `.unless` is coming from `express-unless`.

This should probably be made more clear in the documentation so that other developers can find the correct documentation to read without having to dive into the code.

Thanks.

**Comment by twistedstream** [comment]
@alanjames1987 this sounds like a good suggestion to me. You should open a PR with the README change that you think would have saved you the hassle of digging into the source.

**Comment by alanjames1987** [comment]
Good idea. I have made added just a bit of information and created a pull request.

Thanks.

**Comment by goncaloneves** [comment]
@twistedstream I had this issue, to have exceptions depending on request method.
Could do a PR on readme with an example very suitable for this, such as:

```javascript
app.use(jwt({ secret: 'shhhhhhared-secret'}).unless(function(req) {
  return (
  	req.originalUrl === '/endpoint1' && req.method === 'GET' ||
    req.originalUrl === '/endpoint2' && req.method === 'POST'
  );
}));
```

**Comment by ajbraus** [comment]
+1

**Comment by mattkenefick** [comment]
+1

**Comment by rphovley** [comment]
+1
