### ISSUE TITLE
req.user is out of date

### ISSUE THREAD

**Issue by emps** [auth0/express-jwt#83]
req.user set with user that taken from the jwt that is out of date when user get updated in the db,
this should be fixed

**Comment by root-io** [comment]
I'm stuck on the same problem, I tried to update req.user, but it's not working. Any idea ?

**Comment by jfromaniello** [comment]
This is not a problem of the library itself but a design problem in the token and the application. Let me try to explain.

One way to do this token-based authentication it is to put all user properties in the token and decode/validate the token on every request. This has the disadvantage that the user is sending a long token on every request and that some properties might be outdated.

Another way is to just put the user_id or something that doesn't change and query your database on every request. Example:

```javascript
app.use(expressJwt({secret: 'my-secret', requestProperty: 'token' });
app.use(function (req, res, next) {
  getUser(req.token.user_id, function ( err, user ) {
     if (err) return next(err);
     req.user = user;
     next();
  });
});
```

**Comment by root-io** [comment]
Thanks @jfromaniello
