### ISSUE TITLE
Check against multiple issuers.

### ISSUE THREAD

**Issue by adam-back** [auth0/express-jwt#84]
Hi Team!

Thanks for the middleware! 

Can we build in the option to have checks against multiple issuers? It may look something like this: 
```javascript
jwt({ secret: 'shhhhhhared-secret',
  audience: 'http://myapi/protected',
  issuer: ['http://issuer1', 'http://issuer2'] })
```

I looked into express-jwt's `index.js` and noticed that [it all boils down to the use of jwt.verify()](https://github.com/auth0/express-jwt/blob/master/lib/index.js#L108-L113) from [jsonwebtoken](https://github.com/auth0/node-jsonwebtoken/). 

Someone actually asked how to do this in the [JWT-issues](https://github.com/auth0/node-jsonwebtoken/issues/35). Ultimately, the suggestion is to decode, then check against options:
```javascript
var expected_issuers = ['issuer1', 'issuer2'];
var decoded = jwt.verify(token, 'secret');
if (expected_issuers.indexOf(decoded.iss) === -1) {
  console.log('unexpected issuer for token');
}
```

Is this something that we could support? I'd be happy to contribute.

Adam

**Comment by k-sorrels** [comment]
This is possible actually.  You can use the Payload given to the secret callback function. The payload is a JWT.decode() which is not a validator only a decoder. Once the secret is obtained it then does the verify.
For your use case you can just put it in an array:
```javascript
var expectedIssuers = ['b1.com','2.com','3.com'];

var getSecret = function(req,payload,done){
    if(expectedIssuers.indexOf(payload.iss) >0){
        done(null,secret)
    }else{
        done(new Error('This issuer is not authorized'));
    }
}
```

 Or you can validate a request Ip against an issuer, you can then even return the proper secret for each issuer: 


```javascript
var getSecret = function(req,payload,done){
  if ( (req.ip == ip1 && payload.iss =='domain1') 
     || (req.ip == ip2 && payload.iss =='domain2.com') ){
          return done(null,'domain1And2Secret');
     }
}
```

In the context of the secret call back function the pay load looks like: 

```javascript
{
iss: 'issuer.com',
exp:'142065001',
aud: ' yourapp.com'
}
```
It will also contain any additional indexes you made with the JWT.

Hope it helps!

**Comment by jfromaniello** [comment]
I agree with  @k-sorrels in this case, thanks !

**Comment by mzahidriaz-tr** [comment]
JWT is now supporting multiple issuers  using array
[jwt.verify](https://github.com/auth0/node-jsonwebtoken/blob/74d5719bd03993fcf71e3b176621f133eb6138c0/verify.js#L171)
