### ISSUE TITLE
Best way to check user scopes

### ISSUE THREAD

**Issue by soichih** [auth0/express-jwt#85]
How can I check to make sure if user's jwt token contains certain scopes?

For example, if the user's JWT contains

```
{ iss: 'http://myapp.iu.edu/auth',
  exp: 1451426441.837,
  iat: 1435874441.837,
  scopes: { common: [ 'do123', 'do456', 'do789' ] },
  sub: '5595b489131dad691a58703d' }
```

Then, on the server side, I want to make sure that user is authorized for certain tokens by doing something like

```
router.get('/profile', jwt({secret: publicKey, scopes: {common: 'do123'}}), function(req, res, next) {
    //do 123
});
```

The README says express-jwt checks for audience, and issuer, but doesn't say anything about scope (and above code doesn't work.. it let user access without any scopes). Is there anyway express-jwt can check for scopes? Or if it's not express-jwt's responsibility, is there a module that does?

**Comment by jfromaniello** [comment]
This is outside of the scope of this module, looks like you need a middleware like this:

```js
function require_scope (scopes) {
  return function (req, res, next) {
    var has_scopes = scopes.every(function (scope) {
       return req.token.indexOf(scope) > -1;
    });

    if (!has_scopes) { res.send(401; }
   
    next();
  };
}
```

**Comment by soichih** [comment]
@jfromaniello  Thanks!
