### ISSUE TITLE
make path unprotected( path with parameters still need authorization )

### ISSUE THREAD

**Issue by juneril** [auth0/express-jwt#86]
app.use(jwt({ secret: 'shhhhhhared-secret'}).unless({path: [''/jobs/:category/:company/:title/:id'']}));

**Comment by muraliselvaraj** [comment]
@juneril visit @ http://stackoverflow.com/questions/30559158/handling-parameterised-routes-in-express-jwt-using-unless

**Comment by juneril** [comment]
thank you very much sir
