### ISSUE TITLE
Not throwing unauthorized errors

### ISSUE THREAD

**Issue by k-sorrels** [auth0/express-jwt#88]
As per your documentation, In the secret callback function I will throw errors. I'm listening for an 'UnauthorizedError' in my middle ware to catch it (also per your documentation). The code on line 100 (index.js) doesn't hijack the error and make it an UnauthorizedError neither does it continue with validation. This allows unauthorized usage. 

suggested change: 

100: ` if (err) { return next(err); }`

to 

100:` if(err) { return next(new UnauthorizedError(err))}`

**Comment by k-sorrels** [comment]
https://github.com/auth0/express-jwt/pull/89

**Comment by k-sorrels** [comment]
Proposed change fixed in : https://github.com/auth0/express-jwt/pull/89

**Comment by darkenedsky** [comment]
+1

**Comment by dschenkelman** [comment]
Hey k-sorrels,

Thanks for the proposal. This is a breaking change and some users might not want to actually want to use that error.

Would instead exposing the `UnauthorizedError` so module users can throw it make better sense?

**Comment by k-sorrels** [comment]
Passes now. My bad.

I would like to think that this is an authorization issue and would still deem it necessary to throw UnauthorizedError as this is an error during the auth process. The user should already be catching the error this will throw. I'm struggling to find a case where you would prefer catch the regular error. I'm calling a module to authorize a user, as such I presume one of two events will happen: authorization or failed authorization. You can catch Unauthorized Errors and presume that if there was no error during the authorization that you were in fact authorized.

**Comment by jfromaniello** [comment]
This has been solved long ago..
