### ISSUE TITLE
Preflight OPTIONS fails with custom getToken

### ISSUE THREAD

**Issue by geoguide** [auth0/express-jwt#90]
If I set getToken to read out of a different header name the OPTIONS fails (401). If I do `credentialsRequired: false` it works and reads the token properly, but then all the endpoints are open to the world. 

What am I missing?

	app.use('/admin', expressJwt({
		secret: config.admin_secret, 
		getToken: function customToken(req){
		if (req.headers.authorization && req.headers.authorization.split(' ')[0] == 'Bearer') {
			console.log('using auth');
				return req.headers.authorization.split(' ')[1];
			} else if (req.headers.custom && req.headers.custom.split(' ')[0] == 'Bearer'){
				console.log('using custom');
				return req.headers.custom.split(' ')[1];
			} 
			return null;
		}
	})

edit: using v3.0.1

**Comment by geoguide** [comment]
The solution was that you still have to send the 'Authorization' header. I just set it to blank and it worked.

**Comment by kivervinicius** [comment]
This is not the best option, the best would be that you have become an option for specifying the token is being expected.

like this.

`
if (req.method === 'OPTIONS' && req.headers.hasOwnProperty('access-control-request-headers')) {
      var hasAuthInAccessControl = !!~req.headers['access-control-request-headers']
                                    .split(',').map(function (header) {
                                      return header.trim();
                                    }).indexOf('authorization');

      if (hasAuthInAccessControl) {
        return next();
      }
    }
`
`

if (req.method === 'OPTIONS' && req.headers.hasOwnProperty('access-control-request-headers')) {
      var hasAuthInAccessControl = !!~req.headers['access-control-request-headers']
                                    .split(',').map(function (header) {
                                      return header.trim();
                                    }).indexOf(options.token);

      if (hasAuthInAccessControl) {
        return next();
      }
    }
`

**Comment by kivervinicius** [comment]
I create a pull request for this, check please.

**Comment by jfromaniello** [comment]
The PR was merged long ago, closing this
